version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=cleanarch
      - POSTGRES_USER=cleanarch
      - POSTGRES_PASSWORD=cleanarch
    expose:
      - '5432'
    ports:
      - '5432:5432'
